"""Renderer: implements the Renderer contract from module_contracts.md.

Reads ``Maze`` and ``RenderGameState``, never mutates either, and
talks to pygame only through ``GraphicsFacade``. Every size comes
from the ``Layout`` it is built with; colours come from ``theme``.

Speed: pixel-by-pixel work happens once. Solid rectangles are built
once per (size, colour) and afterwards drawn with a single blit, the
maze and the HUD backdrop live in a cached background, and one frame
buffer is reused for every frame.
"""

from __future__ import annotations

from pathlib import Path

from pacman.core.entity import GHOST_KINDS, Entity, EntityKind, EntityMode
from pacman.core.movement import MAX_DT
from pacman.maze.model import Cell, Direction, Maze, step
from pacman.render.facade import Buffer, Color, GraphicsFacade
from pacman.render.layout import Layout
from pacman.render.theme import (
    BLOCK_COLOR,
    CHEAT_INDICATOR_COLOR,
    EATEN_COLOR,
    FLOOR_COLOR,
    FRIGHTENED_COLOR,
    GAME_OVER_BACKGROUND,
    GAME_OVER_TITLE_COLOR,
    GHOST_COLORS,
    HUD_BACKGROUND,
    HUD_TEXT_COLOR,
    MENU_BACKGROUND,
    MENU_ITEM_COLOR,
    MENU_SELECTED_COLOR,
    MENU_TITLE_COLOR,
    PACGUM_COLOR,
    PAUSE_BACKGROUND,
    PAUSE_ITEM_COLOR,
    PAUSE_TITLE_COLOR,
    PLAYER_COLOR,
    SCREEN_BACKGROUND,
    SCREEN_TEXT_COLOR,
    SCREEN_TITLE_COLOR,
    SUPER_PACGUM_COLOR,
    VICTORY_BACKGROUND,
    VICTORY_TEXT_COLOR,
    VICTORY_TITLE_COLOR,
    WALL_COLOR,
)
from pacman.render.view_state import RenderGameState
from pacman.ui.state_machine import (
    MAIN_MENU_LABELS,
    AppState,
    GameOverPayload,
    HighscoresPayload,
    MainMenuPayload,
    NameEntryPayload,
    VictoryPayload,
    _MAIN_MENU_ORDER,
)


class Renderer:
    """Draws the maze, the game and every screen via a GraphicsFacade."""

    def __init__(self, facade: GraphicsFacade, layout: Layout) -> None:
        """Store the facade and the run's fixed layout.

        Args:
            facade: Graphics facade to draw through.
            layout: Pixel sizes for the whole run (decision D3).
        """
        self._facade = facade
        self._layout = layout
        self._background: Buffer | None = None
        self._origin = (0, 0)
        self._frame = facade.new_buffer(
            layout.window_width, layout.window_height
        )
        self._solids: dict[tuple[int, int, Color], Buffer] = {}
        # Sprite frames pregenerated by assets/upscale.py (exact
        # nearest-neighbor, no runtime scaling). Missing dir (tile
        # other than the generated one) falls back to squares.
        self._sprites: dict[str, Buffer] = {}
        self._sprite_dir = (
            Path(__file__).resolve().parents[2]
            / "assets"
            / "gen"
            / f"tile{layout.tile}"
        )
        self._last_dir: dict[EntityKind, Direction] = {}
        self._last_xy: dict[EntityKind, tuple[int, int]] = {}
        # Game-time clock for sprite animation. Advanced explicitly
        # via advance(), which the main loop calls only with the same
        # dt it feeds tick() — so pause freezes mouths and blinking
        # together with the simulation (REQ-108/109).
        self._anim_t: float = 0.0

    def advance(self, dt: float) -> None:
        """Move the animation clock by one simulated step.

        Args:
            dt: Seconds simulated this frame; clamped like tick().
        """
        if dt > 0.0:
            self._anim_t += min(dt, MAX_DT)

    def cell_to_screen(
        self, cell: Cell, progress_x: float = 0.0, progress_y: float = 0.0
    ) -> tuple[int, int]:
        """Top-left pixel of a cell, optionally shifted by a tile fraction."""
        return self._layout.cell_origin(
            self._origin, cell.col + progress_x, cell.row + progress_y
        )

    def prepare_level(self, maze: Maze) -> None:
        """Render the static maze and HUD backdrop once into a cache.

        Args:
            maze: The level's maze.
        """
        layout = self._layout
        self._origin = layout.maze_origin(maze.width, maze.height)
        buffer = self._facade.new_buffer(
            layout.window_width, layout.window_height
        )
        self._facade.clear(buffer, FLOOR_COLOR)
        for row in range(maze.height):
            for col in range(maze.width):
                cell = Cell(col, row)
                if cell in maze.blocks:
                    self._fill_tile(buffer, cell, BLOCK_COLOR)
                    self._draw_block_rim(buffer, cell, maze)
                    continue
                for direction in Direction:
                    if maze.is_wall_between(cell, direction):
                        self._draw_wall_edge(buffer, cell, direction)
        self._fill_rect(
            buffer,
            0,
            layout.hud_top,
            layout.window_width,
            layout.hud_height,
            HUD_BACKGROUND,
        )
        self._background = buffer

    def draw_game(self, state: RenderGameState) -> None:
        """Draw the cached maze, then pickups, entities and the HUD text.

        Args:
            state: Current game state. Never mutated.
        """
        if self._background is None:
            raise RuntimeError("draw_game called before prepare_level")
        frame = self._frame
        self._facade.blit(self._background, (0, 0), dest=frame)

        for cell in state.core.pacgums:
            self._draw_pickup(frame, cell, "dot_small")
        for cell in state.core.super_pacgums:
            self._draw_pickup(frame, cell, "dot_big")
        self._draw_player(frame, state.core.player)
        for ghost in state.core.ghosts:
            self._draw_ghost(frame, ghost, state.core.frightened_remaining)
        self._draw_hud(frame, state)

        self._facade.blit(frame, (0, 0))

    def present(self) -> None:
        """Push the composited frame to the window."""
        self._facade.present()

    # ---- drawing helpers ------------------------------------------

    def _solid(self, width: int, height: int, color: Color) -> Buffer:
        """A solid-colour buffer, built pixel by pixel once and cached.

        Filling a rectangle pixel by pixel costs width*height Python
        calls every time; blitting a cached buffer costs one. Built
        with put_pixel (not fill) to stay inside the approved primitives.
        """
        key = (width, height, color)
        solid = self._solids.get(key)
        if solid is None:
            solid = self._facade.new_buffer(width, height)
            for y in range(height):
                for x in range(width):
                    self._facade.put_pixel(solid, x, y, color)
            self._solids[key] = solid
        return solid

    def _fill_rect(
        self,
        buffer: Buffer,
        x: int,
        y: int,
        width: int,
        height: int,
        color: Color,
    ) -> None:
        """Draw a solid rectangle by blitting a cached solid buffer."""
        self._facade.blit(
            self._solid(width, height, color), (x, y), dest=buffer
        )

    def _fill_tile(self, buffer: Buffer, cell: Cell, color: Color) -> None:
        """Fill one whole tile."""
        x, y = self.cell_to_screen(cell)
        tile = self._layout.tile
        self._fill_rect(buffer, x, y, tile, tile, color)

    def _draw_block_rim(
        self, buffer: Buffer, cell: Cell, maze: Maze
    ) -> None:
        """Bright rim on block sides facing a corridor.

        The TileSet has no tileable thin-wall set for generated
        mazes (verified by scan), so the logo mass keeps vector
        styling: sheet fill plus a neon rim where it meets play.
        """
        x, y = self.cell_to_screen(cell)
        tile = self._layout.tile
        rim = max(2, self._layout.wall // 2)
        for direction in Direction:
            neighbour = step(cell, direction)
            if neighbour in maze.blocks:
                continue
            if direction is Direction.UP:
                self._fill_rect(buffer, x, y, tile, rim, WALL_COLOR)
            elif direction is Direction.DOWN:
                self._fill_rect(
                    buffer, x, y + tile - rim, tile, rim, WALL_COLOR
                )
            elif direction is Direction.LEFT:
                self._fill_rect(buffer, x, y, rim, tile, WALL_COLOR)
            elif direction is Direction.RIGHT:
                self._fill_rect(
                    buffer, x + tile - rim, y, rim, tile, WALL_COLOR
                )

    def _draw_wall_edge(
        self, buffer: Buffer, cell: Cell, direction: Direction
    ) -> None:
        """Draw the wall segment on one edge of one tile."""
        x, y = self.cell_to_screen(cell)
        tile = self._layout.tile
        wall = self._layout.wall
        if direction is Direction.UP:
            self._fill_rect(buffer, x, y, tile, wall, WALL_COLOR)
        elif direction is Direction.DOWN:
            self._fill_rect(buffer, x, y + tile - wall, tile, wall, WALL_COLOR)
        elif direction is Direction.LEFT:
            self._fill_rect(buffer, x, y, wall, tile, WALL_COLOR)
        elif direction is Direction.RIGHT:
            self._fill_rect(buffer, x + tile - wall, y, wall, tile, WALL_COLOR)

    def _sprite(self, name: str) -> Buffer | None:
        """One pregenerated frame, or None when the tile set is absent."""
        if name in self._sprites:
            return self._sprites[name]
        path = self._sprite_dir / f"{name}.png"
        if not path.is_file():
            return None
        sprite = self._facade.load_image(path)
        self._sprites[name] = sprite
        return sprite

    def _blit_frame(
        self, buffer: Buffer, sprite: Buffer, x: int, y: int
    ) -> None:
        """Blit one frame at a tile origin, no scaling or queries.

        Frames are authored at exactly the tile size (D2), so no
        centering math and no size queries are needed. Eyes frames
        are half-height by construction; callers offset them.
        """
        self._facade.blit(sprite, (x, y), dest=buffer)

    def _draw_pickup(self, buffer: Buffer, cell: Cell, name: str) -> None:
        """Draw a pacgum sprite, falling back to a distinct square."""
        sprite = self._sprite(name)
        x, y = self.cell_to_screen(cell)
        if sprite is None:
            if name == "dot_big":
                radius, color = (
                    self._layout.super_radius,
                    SUPER_PACGUM_COLOR,
                )
            else:
                radius, color = (
                    self._layout.pacgum_radius,
                    PACGUM_COLOR,
                )
            half = self._layout.tile // 2
            self._fill_rect(
                buffer, x + half - radius, y + half - radius,
                radius * 2 + 1, radius * 2 + 1, color,
            )
            return
        self._blit_frame(buffer, sprite, x, y)

    def _entity_xy(self, entity: Entity) -> tuple[int, int]:
        """Interpolated top-left pixel of an entity's tile."""
        col = entity.prev_cell.col + (
            entity.cell.col - entity.prev_cell.col
        ) * entity.progress
        row = entity.prev_cell.row + (
            entity.cell.row - entity.prev_cell.row
        ) * entity.progress
        return self._layout.cell_origin(self._origin, col, row)

    def _facing(self, entity: Entity) -> Direction | None:
        """Current direction, else the last nonzero one (sprite keeps it)."""
        if entity.direction is not None:
            self._last_dir[entity.kind] = entity.direction
            return entity.direction
        return self._last_dir.get(entity.kind)

    # Mouth frames. The sheet ships RIGHT mouths only; LEFT/UP/DOWN
    # rows (same 4-phase layout, 32px cells, pm_left_*/pm_up_*/pm_down_*
    # names) plug into _draw_player once the artist adds them.
    _PM_RIGHT = (
        "pm_right_0",
        "pm_right_1",
        "pm_right_2",
        "pm_right_3",
    )
    _PM_CLOSED = "pm_right_3"

    def _draw_player(self, buffer: Buffer, player: Entity) -> None:
        """Visible chomp while walking (5 Hz), closed mouth when idle."""
        x, y = self._entity_xy(player)
        moving = (x, y) != self._last_xy.get(player.kind)
        self._last_xy[player.kind] = (x, y)
        self._facing(player)  # remember last nonzero direction
        if moving:
            name = self._PM_RIGHT[int(self._anim_t * 5) % 4]
        else:
            name = self._PM_CLOSED
        sprite = self._sprite(name)
        if sprite is None:
            margin = self._layout.entity_margin
            size = self._layout.tile - 2 * margin
            self._fill_rect(
                buffer, x + margin, y + margin,
                size, size, PLAYER_COLOR,
            )
            return
        self._blit_frame(buffer, sprite, x, y)

    def _draw_ghost(
        self, buffer: Buffer, ghost: Entity, frightened_remaining: float
    ) -> None:
        """Body by color and mode, directional eyes on top when normal."""
        try:
            kind_index = GHOST_KINDS.index(ghost.kind)
        except ValueError:
            kind_index = 0
        phase = int(self._anim_t * 8) % 4
        x, y = self._entity_xy(ghost)
        if ghost.mode is EntityMode.EATEN:
            eye = self._EYE_BY_DIR.get(self._facing(ghost), 1)
            eyes = self._sprite(f"eyes_{eye}")
            if eyes is None:
                self._fill_square(buffer, x, y, EATEN_COLOR)
                return
            self._blit_frame(buffer, eyes, x, y + self._layout.tile // 4)
            return
        if ghost.mode is EntityMode.FRIGHTENED:
            if frightened_remaining < 2.0 and int(self._anim_t * 4) % 2:
                names = ["ghost_blink_0", "ghost_blink_1"]
            else:
                names = ["ghost_fright_0", "ghost_fright_1"]
            sprite = self._sprite(names[int(self._anim_t * 8) % 2])
            if sprite is None:
                self._fill_square(buffer, x, y, FRIGHTENED_COLOR)
                return
            self._blit_frame(buffer, sprite, x, y)
            return
        sprite = self._sprite(f"ghost_{kind_index}_{phase}")
        if sprite is None:
            self._fill_square(buffer, x, y, self._ghost_color(ghost))
            return
        self._blit_frame(buffer, sprite, x, y)
        eye = self._EYE_BY_DIR.get(self._facing(ghost), 1)
        eyes = self._sprite(f"eyes_{eye}")
        if eyes is not None:
            self._blit_frame(buffer, eyes, x, y + self._layout.tile // 4)

    _EYE_BY_DIR: dict[Direction | None, int] = {
        Direction.LEFT: 0,
        Direction.RIGHT: 1,
        Direction.UP: 2,
        Direction.DOWN: 3,
        None: 1,
    }

    def _fill_square(
        self, buffer: Buffer, x: int, y: int, color: Color
    ) -> None:
        """Fallback square when a sprite set is missing."""
        margin = self._layout.entity_margin
        size = self._layout.tile - 2 * margin
        self._fill_rect(buffer, x + margin, y + margin, size, size, color)

    def _ghost_color(self, ghost: Entity) -> Color:
        """Pick a ghost's colour from its mode and identity (fallback)."""
        if ghost.mode is EntityMode.EATEN:
            return EATEN_COLOR
        if ghost.mode is EntityMode.FRIGHTENED:
            return FRIGHTENED_COLOR
        return GHOST_COLORS[ghost.kind]

    def _draw_hud(self, buffer: Buffer, state: RenderGameState) -> None:
        """Draw the HUD text; the strip is part of the cached backdrop."""
        layout = self._layout
        text = (
            f"Score: {state.core.score}  Lives: {state.core.lives}  "
            f"Level: {state.core.level_index + 1}/{state.core.level_count}  "
            f"Time: {int(state.core.time_remaining)}"
        )
        self._facade.draw_text(
            buffer, text, (4, layout.hud_top + 2), HUD_TEXT_COLOR
        )
        if state.cheats.enabled:
            labels = ["Cheats ON"]
            if state.cheats.invincible:
                labels.append("Invincible")
            if state.cheats.fast:
                labels.append("Fast x2")
            self._facade.draw_text(
                buffer,
                f"[{', '.join(labels)}]",
                (4, layout.hud_top + layout.font_size + 2),
                CHEAT_INDICATOR_COLOR,
            )

    # ---- screens (split out in refactor step 4) -------------------

    def draw_screen(self, app_state: AppState, payload: object) -> None:
        """Draw a non-gameplay screen.

        Never raises on bad input (REQ-003): wrong payload types
        raise TypeError explicitly (asserts vanish under python -O),
        and PLAYING/EXIT are harmless no-ops (draw_game owns PLAYING).

        Args:
            app_state: Which screen to draw.
            payload: Screen-specific data.
        """
        frame = self._frame
        if app_state is AppState.MAIN_MENU:
            if not isinstance(payload, MainMenuPayload):
                raise TypeError(
                    f"MAIN_MENU needs MainMenuPayload, got {type(payload)}"
                )
            self._facade.clear(frame, MENU_BACKGROUND)
            self._draw_main_menu(frame, payload)
        elif app_state is AppState.PAUSED:
            self._facade.clear(frame, PAUSE_BACKGROUND)
            self._draw_paused(frame)
        elif app_state is AppState.VICTORY:
            if not isinstance(payload, VictoryPayload):
                raise TypeError(
                    f"VICTORY needs VictoryPayload, got {type(payload)}"
                )
            self._facade.clear(frame, VICTORY_BACKGROUND)
            self._draw_victory(frame, payload)
        elif app_state is AppState.GAME_OVER:
            if not isinstance(payload, GameOverPayload):
                raise TypeError(
                    f"GAME_OVER needs GameOverPayload, got {type(payload)}"
                )
            self._facade.clear(frame, GAME_OVER_BACKGROUND)
            self._draw_game_over(frame, payload)
        elif app_state is AppState.NAME_ENTRY:
            if not isinstance(payload, NameEntryPayload):
                raise TypeError(
                    f"NAME_ENTRY needs NameEntryPayload, got {type(payload)}"
                )
            self._facade.clear(frame, SCREEN_BACKGROUND)
            self._draw_name_entry(frame, payload)
        elif app_state is AppState.HIGHSCORES:
            if not isinstance(payload, HighscoresPayload):
                raise TypeError(
                    "HIGHSCORES needs HighscoresPayload, "
                    f"got {type(payload)}"
                )
            self._facade.clear(frame, SCREEN_BACKGROUND)
            self._draw_highscores(frame, payload)
        elif app_state is AppState.INSTRUCTIONS:
            self._facade.clear(frame, SCREEN_BACKGROUND)
            self._draw_instructions(frame)
        else:
            return
        self._facade.blit(frame, (0, 0))

    def _draw_main_menu(
        self, buffer: Buffer, payload: MainMenuPayload
    ) -> None:
        """Title and the four menu entries, the selected one highlighted."""
        step = self._layout.font_size + 12
        self._facade.draw_text(
            buffer, "Pac-Man", (20, 20), MENU_TITLE_COLOR
        )
        start_y = 20 + self._layout.font_size + 24
        for index, item in enumerate(_MAIN_MENU_ORDER):
            y = start_y + index * step
            selected = index == payload.selected_index
            color = MENU_SELECTED_COLOR if selected else MENU_ITEM_COLOR
            prefix = "> " if selected else "  "
            self._facade.draw_text(
                buffer, prefix + MAIN_MENU_LABELS[item], (20, y), color
            )

    def _draw_paused(self, buffer: Buffer) -> None:
        """Pause menu: title and the two options from VI.8."""
        step = self._layout.font_size + 10
        self._facade.draw_text(
            buffer, "Paused", (20, 20), PAUSE_TITLE_COLOR
        )
        self._facade.draw_text(
            buffer, "P - Resume", (20, 20 + step * 2), PAUSE_ITEM_COLOR
        )
        self._facade.draw_text(
            buffer,
            "Esc - Main Menu",
            (20, 20 + step * 3),
            PAUSE_ITEM_COLOR,
        )

    def _draw_victory(self, buffer: Buffer, payload: VictoryPayload) -> None:
        """Victory screen: title, final score, continue hint."""
        step = self._layout.font_size + 10
        self._facade.draw_text(
            buffer, "You Win!", (20, 20), VICTORY_TITLE_COLOR
        )
        self._facade.draw_text(
            buffer,
            f"Final Score: {payload.final_score}",
            (20, 20 + step * 2),
            VICTORY_TEXT_COLOR,
        )
        self._facade.draw_text(
            buffer,
            "Enter/Esc - Continue",
            (20, 20 + step * 3),
            VICTORY_TEXT_COLOR,
        )

    def _draw_game_over(
        self, buffer: Buffer, payload: GameOverPayload
    ) -> None:
        """Game-over screen: title, final score, continue hint."""
        step = self._layout.font_size + 10
        self._facade.draw_text(
            buffer, "Game Over", (20, 20), GAME_OVER_TITLE_COLOR
        )
        self._facade.draw_text(
            buffer,
            f"Final Score: {payload.final_score}",
            (20, 20 + step * 2),
            VICTORY_TEXT_COLOR,
        )
        self._facade.draw_text(
            buffer,
            "Enter/Esc - Continue",
            (20, 20 + step * 3),
            VICTORY_TEXT_COLOR,
        )

    def _draw_name_entry(
        self, buffer: Buffer, payload: NameEntryPayload
    ) -> None:
        """Name entry: title, the name typed so far with a cursor, hint."""
        step = self._layout.font_size + 10
        self._facade.draw_text(
            buffer, "Enter your name:", (20, 20), SCREEN_TITLE_COLOR
        )
        self._facade.draw_text(
            buffer, payload.name + "_", (20, 20 + step * 2), SCREEN_TEXT_COLOR
        )
        self._facade.draw_text(
            buffer,
            "Enter to confirm  Esc to skip",
            (20, 20 + step * 4),
            SCREEN_TEXT_COLOR,
        )
        if payload.cheated:
            self._facade.draw_text(
                buffer,
                "(cheat run - score will not be saved)",
                (20, 20 + step * 5),
                SCREEN_TEXT_COLOR,
            )

    def _draw_highscores(
        self, buffer: Buffer, payload: HighscoresPayload
    ) -> None:
        """Top-10 list: rank, name, score."""
        step = self._layout.font_size + 10
        title_y = 20
        first_y = title_y + self._layout.font_size + 16
        self._facade.draw_text(
            buffer, "High Scores", (20, title_y), SCREEN_TITLE_COLOR
        )
        if not payload.entries:
            self._facade.draw_text(
                buffer, "(no scores yet)", (20, first_y), SCREEN_TEXT_COLOR
            )
        for index, (name, score) in enumerate(payload.entries[:10]):
            line = f"{index + 1}. {name} - {score}"
            self._facade.draw_text(
                buffer, line, (20, first_y + index * step), SCREEN_TEXT_COLOR
            )
        self._facade.draw_text(
            buffer,
            "Esc to return",
            (20, self._layout.window_height - self._layout.font_size - 10),
            SCREEN_TEXT_COLOR,
        )

    def _draw_instructions(self, buffer: Buffer) -> None:
        """Static controls reference (VI.8)."""
        step = self._layout.font_size + 10
        lines = [
            "Controls:",
            "Arrows / WASD - Move",
            "P - Pause",
            "Enter / Space - Confirm",
            "Esc - Back",
            "Cheats: 1 master, 2 invincible, 3 fast,",
            "4 skip level, 5 clear level,",
            "6 fright, 7 lose life",
            "",
            "Esc to return",
        ]
        for index, line in enumerate(lines):
            color = SCREEN_TITLE_COLOR if index == 0 else SCREEN_TEXT_COLOR
            self._facade.draw_text(
                buffer, line, (20, 20 + index * step), color
            )
